//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities1 : DbContext
    {
        public SchoolDBEntities1()
            : base("name=SchoolDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAdminPanelOrderd> TblAdminPanelOrderd { get; set; }
        public virtual DbSet<TblCart> TblCart { get; set; }
        public virtual DbSet<TblClass> TblClass { get; set; }
        public virtual DbSet<TblCountry> TblCountry { get; set; }
        public virtual DbSet<TblCustomer> TblCustomer { get; set; }
        public virtual DbSet<TblDepartment> TblDepartment { get; set; }
        public virtual DbSet<TblEmployee> TblEmployee { get; set; }
        public virtual DbSet<TblEmployee1> TblEmployee1 { get; set; }
        public virtual DbSet<TblFileInfo> TblFileInfo { get; set; }
        public virtual DbSet<TblGuardianDetails> TblGuardianDetails { get; set; }
        public virtual DbSet<TblManager> TblManager { get; set; }
        public virtual DbSet<TblProduct> TblProduct { get; set; }
        public virtual DbSet<TblReturnItems> TblReturnItems { get; set; }
        public virtual DbSet<TblSection> TblSection { get; set; }
        public virtual DbSet<TblState> TblState { get; set; }
        public virtual DbSet<TblStudentDetails> TblStudentDetails { get; set; }
        public virtual DbSet<TblStudentInfo> TblStudentInfo { get; set; }
        public virtual DbSet<TblUser_Mst> TblUser_Mst { get; set; }
    }
}
