//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee1
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpAddr { get; set; }
        public string ContactNo { get; set; }
        public string Pincode { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual TblDepartment TblDepartment { get; set; }
    }
}
