//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Phno { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
        public string City { get; set; }
    }
}
