//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGuardianDetails
    {
        public int GuardianID { get; set; }
        public string GuardianName { get; set; }
        public string Occupation { get; set; }
        public string GuardianAddress { get; set; }
        public string MobileNo { get; set; }
        public string GuardianPincode { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
