//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReturnItems
    {
        public long ReturnID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string OrderdOn { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> RequestOn { get; set; }
        public string Status { get; set; }
    }
}
