//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudentDetails
    {
        public int Sid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string ContactNo { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string RollNo { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TblClass TblClass { get; set; }
        public virtual TblCountry TblCountry { get; set; }
        public virtual TblSection TblSection { get; set; }
        public virtual TblState TblState { get; set; }
    }
}
