//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser_Mst
    {
        public long UserID { get; set; }
        public string MailID { get; set; }
        public string PasswordHash { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Pincode { get; set; }
        public string AadharNo { get; set; }
        public string Gender { get; set; }
        public string PanNo { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
